- name: Install supervisor
  sudo: yes
  apt: pkg=supervisor
       state=latest
       update_cache=yes
  notify: Restart supervisor

- name: Configure supervisor
  template: src=supervisord.conf.j2
            dest=/etc/supervisor/supervisord.conf
  notify: Reload supervisor

- name: Configure supervisor
  template: src=sentry.conf.j2
            dest=/etc/supervisor/conf.d/sentry.conf
  notify: Reload supervisor
