---

- name: Install System Packages
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
  with_items: sys_packages

- name: Install Main Packages
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
  with_items: main_packages
  notify: Restart redis

- name: Copy timezone template
  template: src=timezone.j2
            dest=/etc/timezone

- name: Configure the timezone
  file: src=/usr/share/zoneinfo/{{timezone}}
        dest=/etc/localtime
        state=link
        force=yes
        backup=yes

- name: Set the hostname in /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts
              regexp='^127\.0\.0\.1'
              line='127.0.0.1 localhost {{ hostname }}'
              owner=root
              group=root
              mode=0644
