---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx
       state=latest
       update_cache=yes

- name: Change default nginx site
  template: src={{ ws_template }}
            dest={{ ws_vhost_path }}/{{ ws_vhost_file }}
  notify: restart nginx
