---
- hosts: all
  sudo: yes
  vars:
    web_server: nginx
    servername: sentry.local 192.168.33.90
    timezone: Europe/London
  vars_files:
    - vars/pgsql.yml
    - vars/sentry.yml
    - vars/supervisor.yml
    - vars/common.yml
    - vars/nginx.yml
  roles:
    - common
    - nginx
    - pgsql
    - sentry
    - supervisor
