---

- name: Install virtualenv
  sudo: yes
  pip: name=virtualenv

- name: Install psycopg2 packages
  sudo: yes
  pip:
    name: psycopg2
    virtualenv: /www/sentry
    virtualenv_site_packages: no

- name: Install python-memcached packages
  sudo: yes
  pip:
    name: python-memcached
    virtualenv: /www/sentry
    virtualenv_site_packages: no

- name: Install django-pylibmc packages
  sudo: yes
  pip:
    name: django-pylibmc
    virtualenv: /www/sentry
    virtualenv_site_packages: no

- name: Install Sentry and create virtualenv if needed
  sudo: yes
  pip:
    name: sentry
    virtualenv: /www/sentry/
    virtualenv_site_packages: no

- name: Install Sentry[postgres] and create virtualenv if needed
  sudo: yes
  pip:
    name: sentry[postgres]
    virtualenv: /www/sentry/
    virtualenv_site_packages: no

- name: Install extensions
  pip: name={{item}}
       executable=/www/sentry/bin/pip
  with_items: sentry.extensions

- name: Configure Upstart
  template: src={{item}}.conf.j2
            dest=/etc/init/{{item}}.conf
  with_items:
    - sentry-web
    - sentry-worker

- name: Initialize Sentry config
  sudo: yes
  shell: /www/sentry/bin/sentry init /etc/sentry.conf.py

- name: Change Sentry config
  sudo: yes
  template: src={{ sentry.template }}
            dest=/etc/sentry.conf.py
            owner=root
            group=root
            mode=644

- name: Upgrade Sentry schema
  sudo: yes
  command: /bin/bash -c "./sentry --config=/etc/sentry.conf.py upgrade --noinput"
    chdir=/www/sentry/bin/
  async: 120
  poll: 5

- name: Copy setup config
  template: src=setup.py.j2
            dest="{{sentry.home}}/setup.py"
            owner=root
            group=root
            mode=0755
  register: result_setup

- shell: "{{sentry.home}}/bin/python setup.py"
  sudo: yes
  args:
    chdir: "{{sentry.home}}"
  when: result_setup.changed

- name: Reload supervisor
  shell: supervisorctl reload

- name: Set cron to cleanup Sentry
  cron: name="Cleanup sentry" minute="0" hour="3" job="/www/sentry/bin/sentry cleanup --days=30"
